# Generated by Django 3.2.12 on 2022-02-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220227_1811'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='telegramuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='user_contact_data',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Контактні дані'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='user_preferred_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Як звертатися'),
        ),
    ]
