# Generated by Django 3.2.12 on 2022-02-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220227_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='request_type',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
